In [1]:
import torch
import torchvision

In [28]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.FloatTensor(3, 4, 5)
x

tensor([[[2.7758e-36, 0.0000e+00, 2.9848e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.8788e+31, 1.7220e+22, 2.1715e-18, 2.1511e+23, 1.3435e-05],
         [2.1867e+23, 2.6848e-06, 1.2795e+22, 1.2914e-11, 2.6978e-09]],

        [[1.3445e+22, 2.6582e-06, 2.1707e-18, 4.5447e+30, 7.0062e+22],
         [2.1715e-18, 4.5447e+30, 7.0062e+22, 2.1707e-18, 1.9284e+31],
         [3.2314e-18, 2.4159e-06, 1.6839e+22, 1.0244e-11, 2.1573e-04],
         [8.2292e-10, 2.0971e-07, 3.1986e+21, 1.3458e+22, 5.4646e-05]],

        [[2.5100e-18, 3.1360e+27, 7.0800e+31, 3.1095e-18, 4.7851e+22],
         [2.8826e+32, 4.4248e+30, 7.2442e+22, 2.3086e-12, 7.2646e+22],
         [7.2250e+28, 1.5766e-19, 6.3376e-10, 2.1707e-18, 7.2128e+22],
         [2.1715e-18, 4.1488e-08, 1.0072e-11, 3.0881e-09, 6.6395e-07]]])

In [29]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [30]:
# Приведите его к форме 6 X 10
x = x.view(6, 10)
x

tensor([[2.7758e-36, 0.0000e+00, 2.9848e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.8788e+31, 1.7220e+22, 2.1715e-18, 2.1511e+23, 1.3435e-05, 2.1867e+23,
         2.6848e-06, 1.2795e+22, 1.2914e-11, 2.6978e-09],
        [1.3445e+22, 2.6582e-06, 2.1707e-18, 4.5447e+30, 7.0062e+22, 2.1715e-18,
         4.5447e+30, 7.0062e+22, 2.1707e-18, 1.9284e+31],
        [3.2314e-18, 2.4159e-06, 1.6839e+22, 1.0244e-11, 2.1573e-04, 8.2292e-10,
         2.0971e-07, 3.1986e+21, 1.3458e+22, 5.4646e-05],
        [2.5100e-18, 3.1360e+27, 7.0800e+31, 3.1095e-18, 4.7851e+22, 2.8826e+32,
         4.4248e+30, 7.2442e+22, 2.3086e-12, 7.2646e+22],
        [7.2250e+28, 1.5766e-19, 6.3376e-10, 2.1707e-18, 7.2128e+22, 2.1715e-18,
         4.1488e-08, 1.0072e-11, 3.0881e-09, 6.6395e-07]])

In [31]:
x.shape

torch.Size([6, 10])

In [32]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
y = torch.tensor([1, 4, 2, 2, 1])
print(y.mul_(y))

tensor([ 1, 16,  4,  4,  1])


In [34]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x = x @ x.T
x.shape

torch.Size([6, 6])

In [35]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.], requires_grad = True)
z = torch.tensor([1.], requires_grad = True)
t = torch.tensor([1.], requires_grad = True)

y = x**3 + z - 75 * t

y.backward()

x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [36]:
# Создайте единичный тензор размера 5x6
a = torch.ones(5, 6)

In [37]:
# Переведите его в формат numpy
a = a.numpy()

In [40]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
x = torch.tensor([1.])
w1 = torch.tensor([1.], requires_grad = True)

optimizer = torch.optim.SGD([w1], lr=0.01)
y = x**w1 - 2 * x**2 + 5

# Посчитайте 

In [41]:
optimizer.zero_grad()

In [42]:
y.backward()

In [43]:
optimizer.step()

In [44]:
y

tensor([4.], grad_fn=<AddBackward0>)